---
version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - pip3 install --upgrade cfn-lint
      - node -v
      - npm -v
      - npm i -g npm

  pre_build:
    commands:
      - echo "pre_build steps for revision ${CODEBUILD_RESOLVED_SOURCE_VERSION}..."
      - pwd
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - echo $CODEBUILD_WEBHOOK_BASE_REF
      - echo $CODEBUILD_SRC_DIR
      - env
      - node -v
      - aws --version
      - cfn-lint -v
      - cfn-lint # uses .cfnlintrc
      - npm install

  build:
    commands:
      - echo Build started on `date`
      - echo Building Node app...
      - npm run build
      - npm run test:cypress

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Files
      - ls -la

artifacts:
  files:
    - '**/*'
  base-directory: build

cache:
  paths:
    - '/node_modules/**/*'